# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-19 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=32, null=True, unique=True, verbose_name='邮箱'),
        ),
    ]
